### ISSUE TITLE
Changing Voyager Prefix breaks admin themes path

### ISSUE THREAD

**Issue by impsart** [thedevdojo/voyager-themes#19]
Whenever I try to customize the voyager path prefix... say 
'custom'
```
Route::group(['prefix' => 'custom'], function () {
    Voyager::routes();
});
```

Everything else works except when going to the backend theme directory.

Going to `http://domain.test/custom/themes` results in 404.

Any other config I need to set to fix?

**Comment by giorgosstab** [comment]
@impsart yea because prefix in route change to custom..and prefix in voyager.php config file its admin..
i have 2 different options for you...
1st) let the prefix on config file..and change route like this
Route::group(['prefix' => config('voyager.prefix')], function () {
    Voyager::routes();
});
2nd) add on voyager backend in settings the prefix..
and call its time you want that prefix as settings('here_the_name_of_prefix')

**Comment by impsart** [comment]
Thanks @giorgosstab .. 
Actually made both changes but initially didn't work. 
I had to clear my cache to make it work. Closing.
