### ISSUE TITLE
How to rewite blades?

### ISSUE THREAD

**Issue by donatiss** [thedevdojo/voyager-themes#7]
Could You tell me, how can I rewite index.blade.php file?

**Comment by jeffochoa** [comment]
@tsulavi you have to create your own template folder like `/public/themes/your-theme-name` . Here you have an example [https://github.com/thedevdojo/sample-theme](https://github.com/thedevdojo/sample-theme)

**Comment by chicha2378** [comment]
Since we only deal with layouts in Blade, we only need to load one view. We do not have to deal with controllers or other fancy things.
After setting up our routes, we start our work with the home page. Open app / views / pages / home.blade.php. This file combines a layout file, a page file, and include files. However the fast hosting company like https://www.delighthoster.com/ is required to install the proper functionality of this utility.
